version: '2'
services:
  fouroneone:
    build: .
    ports:
     - "8080:80"
  es:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.4.2"
    environment:
     xpack.security.enabled: 'false'
    ports:
     - "9200:9200"
